# Generated by Django 4.0 on 2023-07-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.IntegerField()),
                ('parent_phone', models.URLField()),
                ('level', models.CharField(choices=[('الصف الاول الثانوي', 'الصف الاول الثانوي'), ('الصف الثاني الثانوي', 'الصف الثاني الثانوي'), ('الصف الثالث الثانوي', 'الصف الثالث الثانوي')], max_length=100)),
                ('student_uuid', models.CharField(max_length=1000)),
            ],
        ),
    ]
