# Generated by Django 4.0 on 2023-07-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_teacher_password_remove_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
