# Generated by Django 4.2.3 on 2023-07-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exam_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='final_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
