# Generated by Django 4.0 on 2023-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_exam_level_alter_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='teacher-images/')),
                ('wa_number', models.URLField(default='')),
                ('is_online', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('teacher_uuid', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
