# Generated by Django 4.0 on 2023-07-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
            preserve_default=False,
        ),
    ]
